# Generated by Django 5.0.3 on 2024-04-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=50),
        ),
    ]
